// Code generated by MockGen. DO NOT EDIT.
// Source: ./contracts (interfaces: Factory)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/mock_factory.go -package mocks -mock_names Factory=MockFactory ./contracts Factory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	contracts "github.com/uagolang/guard/contracts"
	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// GroupPolicy mocks base method.
func (m *MockFactory) GroupPolicy(sub, role contracts.Subject) contracts.GroupPolicy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupPolicy", sub, role)
	ret0, _ := ret[0].(contracts.GroupPolicy)
	return ret0
}

// GroupPolicy indicates an expected call of GroupPolicy.
func (mr *MockFactoryMockRecorder) GroupPolicy(sub, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupPolicy", reflect.TypeOf((*MockFactory)(nil).GroupPolicy), sub, role)
}

// GroupPolicyFromCasbin mocks base method.
func (m *MockFactory) GroupPolicyFromCasbin(p []string) (contracts.GroupPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupPolicyFromCasbin", p)
	ret0, _ := ret[0].(contracts.GroupPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupPolicyFromCasbin indicates an expected call of GroupPolicyFromCasbin.
func (mr *MockFactoryMockRecorder) GroupPolicyFromCasbin(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupPolicyFromCasbin", reflect.TypeOf((*MockFactory)(nil).GroupPolicyFromCasbin), p)
}

// Object mocks base method.
func (m *MockFactory) Object(s contracts.Scope, p contracts.Perm) contracts.Object {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Object", s, p)
	ret0, _ := ret[0].(contracts.Object)
	return ret0
}

// Object indicates an expected call of Object.
func (mr *MockFactoryMockRecorder) Object(s, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Object", reflect.TypeOf((*MockFactory)(nil).Object), s, p)
}

// PolicyFromCasbin mocks base method.
func (m *MockFactory) PolicyFromCasbin(p []string) (contracts.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PolicyFromCasbin", p)
	ret0, _ := ret[0].(contracts.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PolicyFromCasbin indicates an expected call of PolicyFromCasbin.
func (mr *MockFactoryMockRecorder) PolicyFromCasbin(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyFromCasbin", reflect.TypeOf((*MockFactory)(nil).PolicyFromCasbin), p)
}

// RolePoliciesFromCasbin mocks base method.
func (m *MockFactory) RolePoliciesFromCasbin(p [][]string) ([]contracts.RolePolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RolePoliciesFromCasbin", p)
	ret0, _ := ret[0].([]contracts.RolePolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RolePoliciesFromCasbin indicates an expected call of RolePoliciesFromCasbin.
func (mr *MockFactoryMockRecorder) RolePoliciesFromCasbin(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RolePoliciesFromCasbin", reflect.TypeOf((*MockFactory)(nil).RolePoliciesFromCasbin), p)
}

// RolePolicyFromCasbin mocks base method.
func (m *MockFactory) RolePolicyFromCasbin(p []string) (contracts.RolePolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RolePolicyFromCasbin", p)
	ret0, _ := ret[0].(contracts.RolePolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RolePolicyFromCasbin indicates an expected call of RolePolicyFromCasbin.
func (mr *MockFactoryMockRecorder) RolePolicyFromCasbin(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RolePolicyFromCasbin", reflect.TypeOf((*MockFactory)(nil).RolePolicyFromCasbin), p)
}

// Scope mocks base method.
func (m *MockFactory) Scope(data contracts.ScopeData) contracts.Scope {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scope", data)
	ret0, _ := ret[0].(contracts.Scope)
	return ret0
}

// Scope indicates an expected call of Scope.
func (mr *MockFactoryMockRecorder) Scope(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scope", reflect.TypeOf((*MockFactory)(nil).Scope), data)
}

// SubjectGroup mocks base method.
func (m *MockFactory) SubjectGroup(tenantID, id string) contracts.Subject {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubjectGroup", tenantID, id)
	ret0, _ := ret[0].(contracts.Subject)
	return ret0
}

// SubjectGroup indicates an expected call of SubjectGroup.
func (mr *MockFactoryMockRecorder) SubjectGroup(tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubjectGroup", reflect.TypeOf((*MockFactory)(nil).SubjectGroup), tenantID, id)
}

// SubjectRole mocks base method.
func (m *MockFactory) SubjectRole(tenantID, id string) contracts.Subject {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubjectRole", tenantID, id)
	ret0, _ := ret[0].(contracts.Subject)
	return ret0
}

// SubjectRole indicates an expected call of SubjectRole.
func (mr *MockFactoryMockRecorder) SubjectRole(tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubjectRole", reflect.TypeOf((*MockFactory)(nil).SubjectRole), tenantID, id)
}

// SubjectUser mocks base method.
func (m *MockFactory) SubjectUser(id string) contracts.Subject {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubjectUser", id)
	ret0, _ := ret[0].(contracts.Subject)
	return ret0
}

// SubjectUser indicates an expected call of SubjectUser.
func (mr *MockFactoryMockRecorder) SubjectUser(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubjectUser", reflect.TypeOf((*MockFactory)(nil).SubjectUser), id)
}
