// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/casbin/casbin/v2 (interfaces: IEnforcer)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/mock_casbin.go -package mocks -mock_names IEnforcer=MockCasbin github.com/casbin/casbin/v2 IEnforcer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	effector "github.com/casbin/casbin/v2/effector"
	model "github.com/casbin/casbin/v2/model"
	persist "github.com/casbin/casbin/v2/persist"
	rbac "github.com/casbin/casbin/v2/rbac"
	govaluate "github.com/casbin/govaluate"
	gomock "go.uber.org/mock/gomock"
)

// MockCasbin is a mock of IEnforcer interface.
type MockCasbin struct {
	ctrl     *gomock.Controller
	recorder *MockCasbinMockRecorder
	isgomock struct{}
}

// MockCasbinMockRecorder is the mock recorder for MockCasbin.
type MockCasbinMockRecorder struct {
	mock *MockCasbin
}

// NewMockCasbin creates a new mock instance.
func NewMockCasbin(ctrl *gomock.Controller) *MockCasbin {
	mock := &MockCasbin{ctrl: ctrl}
	mock.recorder = &MockCasbinMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCasbin) EXPECT() *MockCasbinMockRecorder {
	return m.recorder
}

// AddFunction mocks base method.
func (m *MockCasbin) AddFunction(name string, function govaluate.ExpressionFunction) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddFunction", name, function)
}

// AddFunction indicates an expected call of AddFunction.
func (mr *MockCasbinMockRecorder) AddFunction(name, function any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFunction", reflect.TypeOf((*MockCasbin)(nil).AddFunction), name, function)
}

// AddGroupingPolicies mocks base method.
func (m *MockCasbin) AddGroupingPolicies(rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGroupingPolicies", rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddGroupingPolicies indicates an expected call of AddGroupingPolicies.
func (mr *MockCasbinMockRecorder) AddGroupingPolicies(rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGroupingPolicies", reflect.TypeOf((*MockCasbin)(nil).AddGroupingPolicies), rules)
}

// AddGroupingPoliciesEx mocks base method.
func (m *MockCasbin) AddGroupingPoliciesEx(rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGroupingPoliciesEx", rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddGroupingPoliciesEx indicates an expected call of AddGroupingPoliciesEx.
func (mr *MockCasbinMockRecorder) AddGroupingPoliciesEx(rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGroupingPoliciesEx", reflect.TypeOf((*MockCasbin)(nil).AddGroupingPoliciesEx), rules)
}

// AddGroupingPolicy mocks base method.
func (m *MockCasbin) AddGroupingPolicy(params ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddGroupingPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddGroupingPolicy indicates an expected call of AddGroupingPolicy.
func (mr *MockCasbinMockRecorder) AddGroupingPolicy(params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGroupingPolicy", reflect.TypeOf((*MockCasbin)(nil).AddGroupingPolicy), params...)
}

// AddNamedGroupingPolicies mocks base method.
func (m *MockCasbin) AddNamedGroupingPolicies(ptype string, rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNamedGroupingPolicies", ptype, rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNamedGroupingPolicies indicates an expected call of AddNamedGroupingPolicies.
func (mr *MockCasbinMockRecorder) AddNamedGroupingPolicies(ptype, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNamedGroupingPolicies", reflect.TypeOf((*MockCasbin)(nil).AddNamedGroupingPolicies), ptype, rules)
}

// AddNamedGroupingPoliciesEx mocks base method.
func (m *MockCasbin) AddNamedGroupingPoliciesEx(ptype string, rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNamedGroupingPoliciesEx", ptype, rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNamedGroupingPoliciesEx indicates an expected call of AddNamedGroupingPoliciesEx.
func (mr *MockCasbinMockRecorder) AddNamedGroupingPoliciesEx(ptype, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNamedGroupingPoliciesEx", reflect.TypeOf((*MockCasbin)(nil).AddNamedGroupingPoliciesEx), ptype, rules)
}

// AddNamedGroupingPolicy mocks base method.
func (m *MockCasbin) AddNamedGroupingPolicy(ptype string, params ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ptype}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddNamedGroupingPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNamedGroupingPolicy indicates an expected call of AddNamedGroupingPolicy.
func (mr *MockCasbinMockRecorder) AddNamedGroupingPolicy(ptype any, params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ptype}, params...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNamedGroupingPolicy", reflect.TypeOf((*MockCasbin)(nil).AddNamedGroupingPolicy), varargs...)
}

// AddNamedPolicies mocks base method.
func (m *MockCasbin) AddNamedPolicies(ptype string, rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNamedPolicies", ptype, rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNamedPolicies indicates an expected call of AddNamedPolicies.
func (mr *MockCasbinMockRecorder) AddNamedPolicies(ptype, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNamedPolicies", reflect.TypeOf((*MockCasbin)(nil).AddNamedPolicies), ptype, rules)
}

// AddNamedPoliciesEx mocks base method.
func (m *MockCasbin) AddNamedPoliciesEx(ptype string, rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNamedPoliciesEx", ptype, rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNamedPoliciesEx indicates an expected call of AddNamedPoliciesEx.
func (mr *MockCasbinMockRecorder) AddNamedPoliciesEx(ptype, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNamedPoliciesEx", reflect.TypeOf((*MockCasbin)(nil).AddNamedPoliciesEx), ptype, rules)
}

// AddNamedPolicy mocks base method.
func (m *MockCasbin) AddNamedPolicy(ptype string, params ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ptype}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddNamedPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNamedPolicy indicates an expected call of AddNamedPolicy.
func (mr *MockCasbinMockRecorder) AddNamedPolicy(ptype any, params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ptype}, params...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNamedPolicy", reflect.TypeOf((*MockCasbin)(nil).AddNamedPolicy), varargs...)
}

// AddPermissionForUser mocks base method.
func (m *MockCasbin) AddPermissionForUser(user string, permission ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{user}
	for _, a := range permission {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddPermissionForUser", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPermissionForUser indicates an expected call of AddPermissionForUser.
func (mr *MockCasbinMockRecorder) AddPermissionForUser(user any, permission ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user}, permission...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPermissionForUser", reflect.TypeOf((*MockCasbin)(nil).AddPermissionForUser), varargs...)
}

// AddPermissionsForUser mocks base method.
func (m *MockCasbin) AddPermissionsForUser(user string, permissions ...[]string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{user}
	for _, a := range permissions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddPermissionsForUser", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPermissionsForUser indicates an expected call of AddPermissionsForUser.
func (mr *MockCasbinMockRecorder) AddPermissionsForUser(user any, permissions ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user}, permissions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPermissionsForUser", reflect.TypeOf((*MockCasbin)(nil).AddPermissionsForUser), varargs...)
}

// AddPolicies mocks base method.
func (m *MockCasbin) AddPolicies(rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPolicies", rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPolicies indicates an expected call of AddPolicies.
func (mr *MockCasbinMockRecorder) AddPolicies(rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPolicies", reflect.TypeOf((*MockCasbin)(nil).AddPolicies), rules)
}

// AddPoliciesEx mocks base method.
func (m *MockCasbin) AddPoliciesEx(rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPoliciesEx", rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPoliciesEx indicates an expected call of AddPoliciesEx.
func (mr *MockCasbinMockRecorder) AddPoliciesEx(rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPoliciesEx", reflect.TypeOf((*MockCasbin)(nil).AddPoliciesEx), rules)
}

// AddPolicy mocks base method.
func (m *MockCasbin) AddPolicy(params ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPolicy indicates an expected call of AddPolicy.
func (mr *MockCasbinMockRecorder) AddPolicy(params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPolicy", reflect.TypeOf((*MockCasbin)(nil).AddPolicy), params...)
}

// AddRoleForUser mocks base method.
func (m *MockCasbin) AddRoleForUser(user, role string, domain ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{user, role}
	for _, a := range domain {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddRoleForUser", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRoleForUser indicates an expected call of AddRoleForUser.
func (mr *MockCasbinMockRecorder) AddRoleForUser(user, role any, domain ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user, role}, domain...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoleForUser", reflect.TypeOf((*MockCasbin)(nil).AddRoleForUser), varargs...)
}

// AddRoleForUserInDomain mocks base method.
func (m *MockCasbin) AddRoleForUserInDomain(user, role, domain string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoleForUserInDomain", user, role, domain)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRoleForUserInDomain indicates an expected call of AddRoleForUserInDomain.
func (mr *MockCasbinMockRecorder) AddRoleForUserInDomain(user, role, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoleForUserInDomain", reflect.TypeOf((*MockCasbin)(nil).AddRoleForUserInDomain), user, role, domain)
}

// BatchEnforce mocks base method.
func (m *MockCasbin) BatchEnforce(requests [][]any) ([]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchEnforce", requests)
	ret0, _ := ret[0].([]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchEnforce indicates an expected call of BatchEnforce.
func (mr *MockCasbinMockRecorder) BatchEnforce(requests any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchEnforce", reflect.TypeOf((*MockCasbin)(nil).BatchEnforce), requests)
}

// BatchEnforceWithMatcher mocks base method.
func (m *MockCasbin) BatchEnforceWithMatcher(matcher string, requests [][]any) ([]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchEnforceWithMatcher", matcher, requests)
	ret0, _ := ret[0].([]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchEnforceWithMatcher indicates an expected call of BatchEnforceWithMatcher.
func (mr *MockCasbinMockRecorder) BatchEnforceWithMatcher(matcher, requests any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchEnforceWithMatcher", reflect.TypeOf((*MockCasbin)(nil).BatchEnforceWithMatcher), matcher, requests)
}

// BuildRoleLinks mocks base method.
func (m *MockCasbin) BuildRoleLinks() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildRoleLinks")
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildRoleLinks indicates an expected call of BuildRoleLinks.
func (mr *MockCasbinMockRecorder) BuildRoleLinks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildRoleLinks", reflect.TypeOf((*MockCasbin)(nil).BuildRoleLinks))
}

// ClearPolicy mocks base method.
func (m *MockCasbin) ClearPolicy() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearPolicy")
}

// ClearPolicy indicates an expected call of ClearPolicy.
func (mr *MockCasbinMockRecorder) ClearPolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearPolicy", reflect.TypeOf((*MockCasbin)(nil).ClearPolicy))
}

// DeleteAllUsersByDomain mocks base method.
func (m *MockCasbin) DeleteAllUsersByDomain(domain string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllUsersByDomain", domain)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAllUsersByDomain indicates an expected call of DeleteAllUsersByDomain.
func (mr *MockCasbinMockRecorder) DeleteAllUsersByDomain(domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllUsersByDomain", reflect.TypeOf((*MockCasbin)(nil).DeleteAllUsersByDomain), domain)
}

// DeleteDomains mocks base method.
func (m *MockCasbin) DeleteDomains(domains ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range domains {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteDomains", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDomains indicates an expected call of DeleteDomains.
func (mr *MockCasbinMockRecorder) DeleteDomains(domains ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDomains", reflect.TypeOf((*MockCasbin)(nil).DeleteDomains), domains...)
}

// DeletePermission mocks base method.
func (m *MockCasbin) DeletePermission(permission ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range permission {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeletePermission", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePermission indicates an expected call of DeletePermission.
func (mr *MockCasbinMockRecorder) DeletePermission(permission ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermission", reflect.TypeOf((*MockCasbin)(nil).DeletePermission), permission...)
}

// DeletePermissionForUser mocks base method.
func (m *MockCasbin) DeletePermissionForUser(user string, permission ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{user}
	for _, a := range permission {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeletePermissionForUser", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePermissionForUser indicates an expected call of DeletePermissionForUser.
func (mr *MockCasbinMockRecorder) DeletePermissionForUser(user any, permission ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user}, permission...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermissionForUser", reflect.TypeOf((*MockCasbin)(nil).DeletePermissionForUser), varargs...)
}

// DeletePermissionsForUser mocks base method.
func (m *MockCasbin) DeletePermissionsForUser(user string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermissionsForUser", user)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePermissionsForUser indicates an expected call of DeletePermissionsForUser.
func (mr *MockCasbinMockRecorder) DeletePermissionsForUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermissionsForUser", reflect.TypeOf((*MockCasbin)(nil).DeletePermissionsForUser), user)
}

// DeleteRole mocks base method.
func (m *MockCasbin) DeleteRole(role string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", role)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockCasbinMockRecorder) DeleteRole(role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockCasbin)(nil).DeleteRole), role)
}

// DeleteRoleForUser mocks base method.
func (m *MockCasbin) DeleteRoleForUser(user, role string, domain ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{user, role}
	for _, a := range domain {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteRoleForUser", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRoleForUser indicates an expected call of DeleteRoleForUser.
func (mr *MockCasbinMockRecorder) DeleteRoleForUser(user, role any, domain ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user, role}, domain...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoleForUser", reflect.TypeOf((*MockCasbin)(nil).DeleteRoleForUser), varargs...)
}

// DeleteRoleForUserInDomain mocks base method.
func (m *MockCasbin) DeleteRoleForUserInDomain(user, role, domain string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoleForUserInDomain", user, role, domain)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRoleForUserInDomain indicates an expected call of DeleteRoleForUserInDomain.
func (mr *MockCasbinMockRecorder) DeleteRoleForUserInDomain(user, role, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoleForUserInDomain", reflect.TypeOf((*MockCasbin)(nil).DeleteRoleForUserInDomain), user, role, domain)
}

// DeleteRolesForUser mocks base method.
func (m *MockCasbin) DeleteRolesForUser(user string, domain ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{user}
	for _, a := range domain {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteRolesForUser", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRolesForUser indicates an expected call of DeleteRolesForUser.
func (mr *MockCasbinMockRecorder) DeleteRolesForUser(user any, domain ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user}, domain...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRolesForUser", reflect.TypeOf((*MockCasbin)(nil).DeleteRolesForUser), varargs...)
}

// DeleteRolesForUserInDomain mocks base method.
func (m *MockCasbin) DeleteRolesForUserInDomain(user, domain string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRolesForUserInDomain", user, domain)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRolesForUserInDomain indicates an expected call of DeleteRolesForUserInDomain.
func (mr *MockCasbinMockRecorder) DeleteRolesForUserInDomain(user, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRolesForUserInDomain", reflect.TypeOf((*MockCasbin)(nil).DeleteRolesForUserInDomain), user, domain)
}

// DeleteUser mocks base method.
func (m *MockCasbin) DeleteUser(user string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", user)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockCasbinMockRecorder) DeleteUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockCasbin)(nil).DeleteUser), user)
}

// EnableAutoBuildRoleLinks mocks base method.
func (m *MockCasbin) EnableAutoBuildRoleLinks(autoBuildRoleLinks bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnableAutoBuildRoleLinks", autoBuildRoleLinks)
}

// EnableAutoBuildRoleLinks indicates an expected call of EnableAutoBuildRoleLinks.
func (mr *MockCasbinMockRecorder) EnableAutoBuildRoleLinks(autoBuildRoleLinks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableAutoBuildRoleLinks", reflect.TypeOf((*MockCasbin)(nil).EnableAutoBuildRoleLinks), autoBuildRoleLinks)
}

// EnableAutoNotifyWatcher mocks base method.
func (m *MockCasbin) EnableAutoNotifyWatcher(enable bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnableAutoNotifyWatcher", enable)
}

// EnableAutoNotifyWatcher indicates an expected call of EnableAutoNotifyWatcher.
func (mr *MockCasbinMockRecorder) EnableAutoNotifyWatcher(enable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableAutoNotifyWatcher", reflect.TypeOf((*MockCasbin)(nil).EnableAutoNotifyWatcher), enable)
}

// EnableAutoSave mocks base method.
func (m *MockCasbin) EnableAutoSave(autoSave bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnableAutoSave", autoSave)
}

// EnableAutoSave indicates an expected call of EnableAutoSave.
func (mr *MockCasbinMockRecorder) EnableAutoSave(autoSave any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableAutoSave", reflect.TypeOf((*MockCasbin)(nil).EnableAutoSave), autoSave)
}

// EnableEnforce mocks base method.
func (m *MockCasbin) EnableEnforce(enable bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnableEnforce", enable)
}

// EnableEnforce indicates an expected call of EnableEnforce.
func (mr *MockCasbinMockRecorder) EnableEnforce(enable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableEnforce", reflect.TypeOf((*MockCasbin)(nil).EnableEnforce), enable)
}

// EnableLog mocks base method.
func (m *MockCasbin) EnableLog(enable bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnableLog", enable)
}

// EnableLog indicates an expected call of EnableLog.
func (mr *MockCasbinMockRecorder) EnableLog(enable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableLog", reflect.TypeOf((*MockCasbin)(nil).EnableLog), enable)
}

// Enforce mocks base method.
func (m *MockCasbin) Enforce(rvals ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range rvals {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Enforce", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockCasbinMockRecorder) Enforce(rvals ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockCasbin)(nil).Enforce), rvals...)
}

// EnforceEx mocks base method.
func (m *MockCasbin) EnforceEx(rvals ...any) (bool, []string, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range rvals {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EnforceEx", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// EnforceEx indicates an expected call of EnforceEx.
func (mr *MockCasbinMockRecorder) EnforceEx(rvals ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnforceEx", reflect.TypeOf((*MockCasbin)(nil).EnforceEx), rvals...)
}

// EnforceExWithMatcher mocks base method.
func (m *MockCasbin) EnforceExWithMatcher(matcher string, rvals ...any) (bool, []string, error) {
	m.ctrl.T.Helper()
	varargs := []any{matcher}
	for _, a := range rvals {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EnforceExWithMatcher", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// EnforceExWithMatcher indicates an expected call of EnforceExWithMatcher.
func (mr *MockCasbinMockRecorder) EnforceExWithMatcher(matcher any, rvals ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{matcher}, rvals...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnforceExWithMatcher", reflect.TypeOf((*MockCasbin)(nil).EnforceExWithMatcher), varargs...)
}

// EnforceWithMatcher mocks base method.
func (m *MockCasbin) EnforceWithMatcher(matcher string, rvals ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{matcher}
	for _, a := range rvals {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EnforceWithMatcher", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnforceWithMatcher indicates an expected call of EnforceWithMatcher.
func (mr *MockCasbinMockRecorder) EnforceWithMatcher(matcher any, rvals ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{matcher}, rvals...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnforceWithMatcher", reflect.TypeOf((*MockCasbin)(nil).EnforceWithMatcher), varargs...)
}

// GetAdapter mocks base method.
func (m *MockCasbin) GetAdapter() persist.Adapter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdapter")
	ret0, _ := ret[0].(persist.Adapter)
	return ret0
}

// GetAdapter indicates an expected call of GetAdapter.
func (mr *MockCasbinMockRecorder) GetAdapter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdapter", reflect.TypeOf((*MockCasbin)(nil).GetAdapter))
}

// GetAllActions mocks base method.
func (m *MockCasbin) GetAllActions() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActions")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllActions indicates an expected call of GetAllActions.
func (mr *MockCasbinMockRecorder) GetAllActions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllActions", reflect.TypeOf((*MockCasbin)(nil).GetAllActions))
}

// GetAllDomains mocks base method.
func (m *MockCasbin) GetAllDomains() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDomains")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDomains indicates an expected call of GetAllDomains.
func (mr *MockCasbinMockRecorder) GetAllDomains() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDomains", reflect.TypeOf((*MockCasbin)(nil).GetAllDomains))
}

// GetAllNamedActions mocks base method.
func (m *MockCasbin) GetAllNamedActions(ptype string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNamedActions", ptype)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNamedActions indicates an expected call of GetAllNamedActions.
func (mr *MockCasbinMockRecorder) GetAllNamedActions(ptype any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNamedActions", reflect.TypeOf((*MockCasbin)(nil).GetAllNamedActions), ptype)
}

// GetAllNamedObjects mocks base method.
func (m *MockCasbin) GetAllNamedObjects(ptype string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNamedObjects", ptype)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNamedObjects indicates an expected call of GetAllNamedObjects.
func (mr *MockCasbinMockRecorder) GetAllNamedObjects(ptype any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNamedObjects", reflect.TypeOf((*MockCasbin)(nil).GetAllNamedObjects), ptype)
}

// GetAllNamedRoles mocks base method.
func (m *MockCasbin) GetAllNamedRoles(ptype string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNamedRoles", ptype)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNamedRoles indicates an expected call of GetAllNamedRoles.
func (mr *MockCasbinMockRecorder) GetAllNamedRoles(ptype any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNamedRoles", reflect.TypeOf((*MockCasbin)(nil).GetAllNamedRoles), ptype)
}

// GetAllNamedSubjects mocks base method.
func (m *MockCasbin) GetAllNamedSubjects(ptype string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNamedSubjects", ptype)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNamedSubjects indicates an expected call of GetAllNamedSubjects.
func (mr *MockCasbinMockRecorder) GetAllNamedSubjects(ptype any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNamedSubjects", reflect.TypeOf((*MockCasbin)(nil).GetAllNamedSubjects), ptype)
}

// GetAllObjects mocks base method.
func (m *MockCasbin) GetAllObjects() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllObjects")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllObjects indicates an expected call of GetAllObjects.
func (mr *MockCasbinMockRecorder) GetAllObjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllObjects", reflect.TypeOf((*MockCasbin)(nil).GetAllObjects))
}

// GetAllRoles mocks base method.
func (m *MockCasbin) GetAllRoles() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRoles")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRoles indicates an expected call of GetAllRoles.
func (mr *MockCasbinMockRecorder) GetAllRoles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRoles", reflect.TypeOf((*MockCasbin)(nil).GetAllRoles))
}

// GetAllRolesByDomain mocks base method.
func (m *MockCasbin) GetAllRolesByDomain(domain string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRolesByDomain", domain)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRolesByDomain indicates an expected call of GetAllRolesByDomain.
func (mr *MockCasbinMockRecorder) GetAllRolesByDomain(domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRolesByDomain", reflect.TypeOf((*MockCasbin)(nil).GetAllRolesByDomain), domain)
}

// GetAllSubjects mocks base method.
func (m *MockCasbin) GetAllSubjects() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSubjects")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSubjects indicates an expected call of GetAllSubjects.
func (mr *MockCasbinMockRecorder) GetAllSubjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSubjects", reflect.TypeOf((*MockCasbin)(nil).GetAllSubjects))
}

// GetAllUsersByDomain mocks base method.
func (m *MockCasbin) GetAllUsersByDomain(domain string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsersByDomain", domain)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsersByDomain indicates an expected call of GetAllUsersByDomain.
func (mr *MockCasbinMockRecorder) GetAllUsersByDomain(domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsersByDomain", reflect.TypeOf((*MockCasbin)(nil).GetAllUsersByDomain), domain)
}

// GetFilteredGroupingPolicy mocks base method.
func (m *MockCasbin) GetFilteredGroupingPolicy(fieldIndex int, fieldValues ...string) ([][]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{fieldIndex}
	for _, a := range fieldValues {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFilteredGroupingPolicy", varargs...)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilteredGroupingPolicy indicates an expected call of GetFilteredGroupingPolicy.
func (mr *MockCasbinMockRecorder) GetFilteredGroupingPolicy(fieldIndex any, fieldValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{fieldIndex}, fieldValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilteredGroupingPolicy", reflect.TypeOf((*MockCasbin)(nil).GetFilteredGroupingPolicy), varargs...)
}

// GetFilteredNamedGroupingPolicy mocks base method.
func (m *MockCasbin) GetFilteredNamedGroupingPolicy(ptype string, fieldIndex int, fieldValues ...string) ([][]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ptype, fieldIndex}
	for _, a := range fieldValues {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFilteredNamedGroupingPolicy", varargs...)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilteredNamedGroupingPolicy indicates an expected call of GetFilteredNamedGroupingPolicy.
func (mr *MockCasbinMockRecorder) GetFilteredNamedGroupingPolicy(ptype, fieldIndex any, fieldValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ptype, fieldIndex}, fieldValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilteredNamedGroupingPolicy", reflect.TypeOf((*MockCasbin)(nil).GetFilteredNamedGroupingPolicy), varargs...)
}

// GetFilteredNamedPolicy mocks base method.
func (m *MockCasbin) GetFilteredNamedPolicy(ptype string, fieldIndex int, fieldValues ...string) ([][]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ptype, fieldIndex}
	for _, a := range fieldValues {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFilteredNamedPolicy", varargs...)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilteredNamedPolicy indicates an expected call of GetFilteredNamedPolicy.
func (mr *MockCasbinMockRecorder) GetFilteredNamedPolicy(ptype, fieldIndex any, fieldValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ptype, fieldIndex}, fieldValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilteredNamedPolicy", reflect.TypeOf((*MockCasbin)(nil).GetFilteredNamedPolicy), varargs...)
}

// GetFilteredPolicy mocks base method.
func (m *MockCasbin) GetFilteredPolicy(fieldIndex int, fieldValues ...string) ([][]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{fieldIndex}
	for _, a := range fieldValues {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFilteredPolicy", varargs...)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilteredPolicy indicates an expected call of GetFilteredPolicy.
func (mr *MockCasbinMockRecorder) GetFilteredPolicy(fieldIndex any, fieldValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{fieldIndex}, fieldValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilteredPolicy", reflect.TypeOf((*MockCasbin)(nil).GetFilteredPolicy), varargs...)
}

// GetGroupingPolicy mocks base method.
func (m *MockCasbin) GetGroupingPolicy() ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupingPolicy")
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupingPolicy indicates an expected call of GetGroupingPolicy.
func (mr *MockCasbinMockRecorder) GetGroupingPolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupingPolicy", reflect.TypeOf((*MockCasbin)(nil).GetGroupingPolicy))
}

// GetImplicitPermissionsForUser mocks base method.
func (m *MockCasbin) GetImplicitPermissionsForUser(user string, domain ...string) ([][]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{user}
	for _, a := range domain {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetImplicitPermissionsForUser", varargs...)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImplicitPermissionsForUser indicates an expected call of GetImplicitPermissionsForUser.
func (mr *MockCasbinMockRecorder) GetImplicitPermissionsForUser(user any, domain ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user}, domain...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImplicitPermissionsForUser", reflect.TypeOf((*MockCasbin)(nil).GetImplicitPermissionsForUser), varargs...)
}

// GetImplicitRolesForUser mocks base method.
func (m *MockCasbin) GetImplicitRolesForUser(name string, domain ...string) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range domain {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetImplicitRolesForUser", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImplicitRolesForUser indicates an expected call of GetImplicitRolesForUser.
func (mr *MockCasbinMockRecorder) GetImplicitRolesForUser(name any, domain ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, domain...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImplicitRolesForUser", reflect.TypeOf((*MockCasbin)(nil).GetImplicitRolesForUser), varargs...)
}

// GetImplicitUsersForPermission mocks base method.
func (m *MockCasbin) GetImplicitUsersForPermission(permission ...string) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range permission {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetImplicitUsersForPermission", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImplicitUsersForPermission indicates an expected call of GetImplicitUsersForPermission.
func (mr *MockCasbinMockRecorder) GetImplicitUsersForPermission(permission ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImplicitUsersForPermission", reflect.TypeOf((*MockCasbin)(nil).GetImplicitUsersForPermission), permission...)
}

// GetModel mocks base method.
func (m *MockCasbin) GetModel() model.Model {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModel")
	ret0, _ := ret[0].(model.Model)
	return ret0
}

// GetModel indicates an expected call of GetModel.
func (mr *MockCasbinMockRecorder) GetModel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModel", reflect.TypeOf((*MockCasbin)(nil).GetModel))
}

// GetNamedGroupingPolicy mocks base method.
func (m *MockCasbin) GetNamedGroupingPolicy(ptype string) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamedGroupingPolicy", ptype)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNamedGroupingPolicy indicates an expected call of GetNamedGroupingPolicy.
func (mr *MockCasbinMockRecorder) GetNamedGroupingPolicy(ptype any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamedGroupingPolicy", reflect.TypeOf((*MockCasbin)(nil).GetNamedGroupingPolicy), ptype)
}

// GetNamedPolicy mocks base method.
func (m *MockCasbin) GetNamedPolicy(ptype string) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamedPolicy", ptype)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNamedPolicy indicates an expected call of GetNamedPolicy.
func (mr *MockCasbinMockRecorder) GetNamedPolicy(ptype any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamedPolicy", reflect.TypeOf((*MockCasbin)(nil).GetNamedPolicy), ptype)
}

// GetPermissionsForUser mocks base method.
func (m *MockCasbin) GetPermissionsForUser(user string, domain ...string) ([][]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{user}
	for _, a := range domain {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPermissionsForUser", varargs...)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionsForUser indicates an expected call of GetPermissionsForUser.
func (mr *MockCasbinMockRecorder) GetPermissionsForUser(user any, domain ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user}, domain...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionsForUser", reflect.TypeOf((*MockCasbin)(nil).GetPermissionsForUser), varargs...)
}

// GetPermissionsForUserInDomain mocks base method.
func (m *MockCasbin) GetPermissionsForUserInDomain(user, domain string) [][]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionsForUserInDomain", user, domain)
	ret0, _ := ret[0].([][]string)
	return ret0
}

// GetPermissionsForUserInDomain indicates an expected call of GetPermissionsForUserInDomain.
func (mr *MockCasbinMockRecorder) GetPermissionsForUserInDomain(user, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionsForUserInDomain", reflect.TypeOf((*MockCasbin)(nil).GetPermissionsForUserInDomain), user, domain)
}

// GetPolicy mocks base method.
func (m *MockCasbin) GetPolicy() ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicy")
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockCasbinMockRecorder) GetPolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockCasbin)(nil).GetPolicy))
}

// GetRoleManager mocks base method.
func (m *MockCasbin) GetRoleManager() rbac.RoleManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleManager")
	ret0, _ := ret[0].(rbac.RoleManager)
	return ret0
}

// GetRoleManager indicates an expected call of GetRoleManager.
func (mr *MockCasbinMockRecorder) GetRoleManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleManager", reflect.TypeOf((*MockCasbin)(nil).GetRoleManager))
}

// GetRolesForUser mocks base method.
func (m *MockCasbin) GetRolesForUser(name string, domain ...string) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range domain {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRolesForUser", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolesForUser indicates an expected call of GetRolesForUser.
func (mr *MockCasbinMockRecorder) GetRolesForUser(name any, domain ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, domain...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesForUser", reflect.TypeOf((*MockCasbin)(nil).GetRolesForUser), varargs...)
}

// GetRolesForUserInDomain mocks base method.
func (m *MockCasbin) GetRolesForUserInDomain(name, domain string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolesForUserInDomain", name, domain)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetRolesForUserInDomain indicates an expected call of GetRolesForUserInDomain.
func (mr *MockCasbinMockRecorder) GetRolesForUserInDomain(name, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesForUserInDomain", reflect.TypeOf((*MockCasbin)(nil).GetRolesForUserInDomain), name, domain)
}

// GetUsersForRole mocks base method.
func (m *MockCasbin) GetUsersForRole(name string, domain ...string) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range domain {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUsersForRole", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersForRole indicates an expected call of GetUsersForRole.
func (mr *MockCasbinMockRecorder) GetUsersForRole(name any, domain ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, domain...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersForRole", reflect.TypeOf((*MockCasbin)(nil).GetUsersForRole), varargs...)
}

// GetUsersForRoleInDomain mocks base method.
func (m *MockCasbin) GetUsersForRoleInDomain(name, domain string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersForRoleInDomain", name, domain)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetUsersForRoleInDomain indicates an expected call of GetUsersForRoleInDomain.
func (mr *MockCasbinMockRecorder) GetUsersForRoleInDomain(name, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersForRoleInDomain", reflect.TypeOf((*MockCasbin)(nil).GetUsersForRoleInDomain), name, domain)
}

// HasGroupingPolicy mocks base method.
func (m *MockCasbin) HasGroupingPolicy(params ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HasGroupingPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasGroupingPolicy indicates an expected call of HasGroupingPolicy.
func (mr *MockCasbinMockRecorder) HasGroupingPolicy(params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasGroupingPolicy", reflect.TypeOf((*MockCasbin)(nil).HasGroupingPolicy), params...)
}

// HasNamedGroupingPolicy mocks base method.
func (m *MockCasbin) HasNamedGroupingPolicy(ptype string, params ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ptype}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HasNamedGroupingPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasNamedGroupingPolicy indicates an expected call of HasNamedGroupingPolicy.
func (mr *MockCasbinMockRecorder) HasNamedGroupingPolicy(ptype any, params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ptype}, params...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasNamedGroupingPolicy", reflect.TypeOf((*MockCasbin)(nil).HasNamedGroupingPolicy), varargs...)
}

// HasNamedPolicy mocks base method.
func (m *MockCasbin) HasNamedPolicy(ptype string, params ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ptype}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HasNamedPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasNamedPolicy indicates an expected call of HasNamedPolicy.
func (mr *MockCasbinMockRecorder) HasNamedPolicy(ptype any, params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ptype}, params...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasNamedPolicy", reflect.TypeOf((*MockCasbin)(nil).HasNamedPolicy), varargs...)
}

// HasPermissionForUser mocks base method.
func (m *MockCasbin) HasPermissionForUser(user string, permission ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{user}
	for _, a := range permission {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HasPermissionForUser", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPermissionForUser indicates an expected call of HasPermissionForUser.
func (mr *MockCasbinMockRecorder) HasPermissionForUser(user any, permission ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user}, permission...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPermissionForUser", reflect.TypeOf((*MockCasbin)(nil).HasPermissionForUser), varargs...)
}

// HasPolicy mocks base method.
func (m *MockCasbin) HasPolicy(params ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HasPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPolicy indicates an expected call of HasPolicy.
func (mr *MockCasbinMockRecorder) HasPolicy(params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPolicy", reflect.TypeOf((*MockCasbin)(nil).HasPolicy), params...)
}

// HasRoleForUser mocks base method.
func (m *MockCasbin) HasRoleForUser(name, role string, domain ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{name, role}
	for _, a := range domain {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HasRoleForUser", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasRoleForUser indicates an expected call of HasRoleForUser.
func (mr *MockCasbinMockRecorder) HasRoleForUser(name, role any, domain ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name, role}, domain...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasRoleForUser", reflect.TypeOf((*MockCasbin)(nil).HasRoleForUser), varargs...)
}

// InitWithAdapter mocks base method.
func (m *MockCasbin) InitWithAdapter(modelPath string, adapter persist.Adapter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitWithAdapter", modelPath, adapter)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitWithAdapter indicates an expected call of InitWithAdapter.
func (mr *MockCasbinMockRecorder) InitWithAdapter(modelPath, adapter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitWithAdapter", reflect.TypeOf((*MockCasbin)(nil).InitWithAdapter), modelPath, adapter)
}

// InitWithFile mocks base method.
func (m *MockCasbin) InitWithFile(modelPath, policyPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitWithFile", modelPath, policyPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitWithFile indicates an expected call of InitWithFile.
func (mr *MockCasbinMockRecorder) InitWithFile(modelPath, policyPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitWithFile", reflect.TypeOf((*MockCasbin)(nil).InitWithFile), modelPath, policyPath)
}

// InitWithModelAndAdapter mocks base method.
func (m_2 *MockCasbin) InitWithModelAndAdapter(m model.Model, adapter persist.Adapter) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "InitWithModelAndAdapter", m, adapter)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitWithModelAndAdapter indicates an expected call of InitWithModelAndAdapter.
func (mr *MockCasbinMockRecorder) InitWithModelAndAdapter(m, adapter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitWithModelAndAdapter", reflect.TypeOf((*MockCasbin)(nil).InitWithModelAndAdapter), m, adapter)
}

// IsFiltered mocks base method.
func (m *MockCasbin) IsFiltered() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFiltered")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFiltered indicates an expected call of IsFiltered.
func (mr *MockCasbinMockRecorder) IsFiltered() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFiltered", reflect.TypeOf((*MockCasbin)(nil).IsFiltered))
}

// LoadFilteredPolicy mocks base method.
func (m *MockCasbin) LoadFilteredPolicy(filter any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFilteredPolicy", filter)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadFilteredPolicy indicates an expected call of LoadFilteredPolicy.
func (mr *MockCasbinMockRecorder) LoadFilteredPolicy(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFilteredPolicy", reflect.TypeOf((*MockCasbin)(nil).LoadFilteredPolicy), filter)
}

// LoadIncrementalFilteredPolicy mocks base method.
func (m *MockCasbin) LoadIncrementalFilteredPolicy(filter any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadIncrementalFilteredPolicy", filter)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadIncrementalFilteredPolicy indicates an expected call of LoadIncrementalFilteredPolicy.
func (mr *MockCasbinMockRecorder) LoadIncrementalFilteredPolicy(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadIncrementalFilteredPolicy", reflect.TypeOf((*MockCasbin)(nil).LoadIncrementalFilteredPolicy), filter)
}

// LoadModel mocks base method.
func (m *MockCasbin) LoadModel() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadModel")
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadModel indicates an expected call of LoadModel.
func (mr *MockCasbinMockRecorder) LoadModel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadModel", reflect.TypeOf((*MockCasbin)(nil).LoadModel))
}

// LoadPolicy mocks base method.
func (m *MockCasbin) LoadPolicy() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPolicy")
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadPolicy indicates an expected call of LoadPolicy.
func (mr *MockCasbinMockRecorder) LoadPolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPolicy", reflect.TypeOf((*MockCasbin)(nil).LoadPolicy))
}

// RemoveFilteredGroupingPolicy mocks base method.
func (m *MockCasbin) RemoveFilteredGroupingPolicy(fieldIndex int, fieldValues ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{fieldIndex}
	for _, a := range fieldValues {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveFilteredGroupingPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveFilteredGroupingPolicy indicates an expected call of RemoveFilteredGroupingPolicy.
func (mr *MockCasbinMockRecorder) RemoveFilteredGroupingPolicy(fieldIndex any, fieldValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{fieldIndex}, fieldValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFilteredGroupingPolicy", reflect.TypeOf((*MockCasbin)(nil).RemoveFilteredGroupingPolicy), varargs...)
}

// RemoveFilteredNamedGroupingPolicy mocks base method.
func (m *MockCasbin) RemoveFilteredNamedGroupingPolicy(ptype string, fieldIndex int, fieldValues ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ptype, fieldIndex}
	for _, a := range fieldValues {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveFilteredNamedGroupingPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveFilteredNamedGroupingPolicy indicates an expected call of RemoveFilteredNamedGroupingPolicy.
func (mr *MockCasbinMockRecorder) RemoveFilteredNamedGroupingPolicy(ptype, fieldIndex any, fieldValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ptype, fieldIndex}, fieldValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFilteredNamedGroupingPolicy", reflect.TypeOf((*MockCasbin)(nil).RemoveFilteredNamedGroupingPolicy), varargs...)
}

// RemoveFilteredNamedPolicy mocks base method.
func (m *MockCasbin) RemoveFilteredNamedPolicy(ptype string, fieldIndex int, fieldValues ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ptype, fieldIndex}
	for _, a := range fieldValues {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveFilteredNamedPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveFilteredNamedPolicy indicates an expected call of RemoveFilteredNamedPolicy.
func (mr *MockCasbinMockRecorder) RemoveFilteredNamedPolicy(ptype, fieldIndex any, fieldValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ptype, fieldIndex}, fieldValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFilteredNamedPolicy", reflect.TypeOf((*MockCasbin)(nil).RemoveFilteredNamedPolicy), varargs...)
}

// RemoveFilteredPolicy mocks base method.
func (m *MockCasbin) RemoveFilteredPolicy(fieldIndex int, fieldValues ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{fieldIndex}
	for _, a := range fieldValues {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveFilteredPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveFilteredPolicy indicates an expected call of RemoveFilteredPolicy.
func (mr *MockCasbinMockRecorder) RemoveFilteredPolicy(fieldIndex any, fieldValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{fieldIndex}, fieldValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFilteredPolicy", reflect.TypeOf((*MockCasbin)(nil).RemoveFilteredPolicy), varargs...)
}

// RemoveGroupingPolicies mocks base method.
func (m *MockCasbin) RemoveGroupingPolicies(rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveGroupingPolicies", rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveGroupingPolicies indicates an expected call of RemoveGroupingPolicies.
func (mr *MockCasbinMockRecorder) RemoveGroupingPolicies(rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGroupingPolicies", reflect.TypeOf((*MockCasbin)(nil).RemoveGroupingPolicies), rules)
}

// RemoveGroupingPolicy mocks base method.
func (m *MockCasbin) RemoveGroupingPolicy(params ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveGroupingPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveGroupingPolicy indicates an expected call of RemoveGroupingPolicy.
func (mr *MockCasbinMockRecorder) RemoveGroupingPolicy(params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGroupingPolicy", reflect.TypeOf((*MockCasbin)(nil).RemoveGroupingPolicy), params...)
}

// RemoveNamedGroupingPolicies mocks base method.
func (m *MockCasbin) RemoveNamedGroupingPolicies(ptype string, rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveNamedGroupingPolicies", ptype, rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveNamedGroupingPolicies indicates an expected call of RemoveNamedGroupingPolicies.
func (mr *MockCasbinMockRecorder) RemoveNamedGroupingPolicies(ptype, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNamedGroupingPolicies", reflect.TypeOf((*MockCasbin)(nil).RemoveNamedGroupingPolicies), ptype, rules)
}

// RemoveNamedGroupingPolicy mocks base method.
func (m *MockCasbin) RemoveNamedGroupingPolicy(ptype string, params ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ptype}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveNamedGroupingPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveNamedGroupingPolicy indicates an expected call of RemoveNamedGroupingPolicy.
func (mr *MockCasbinMockRecorder) RemoveNamedGroupingPolicy(ptype any, params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ptype}, params...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNamedGroupingPolicy", reflect.TypeOf((*MockCasbin)(nil).RemoveNamedGroupingPolicy), varargs...)
}

// RemoveNamedPolicies mocks base method.
func (m *MockCasbin) RemoveNamedPolicies(ptype string, rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveNamedPolicies", ptype, rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveNamedPolicies indicates an expected call of RemoveNamedPolicies.
func (mr *MockCasbinMockRecorder) RemoveNamedPolicies(ptype, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNamedPolicies", reflect.TypeOf((*MockCasbin)(nil).RemoveNamedPolicies), ptype, rules)
}

// RemoveNamedPolicy mocks base method.
func (m *MockCasbin) RemoveNamedPolicy(ptype string, params ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ptype}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveNamedPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveNamedPolicy indicates an expected call of RemoveNamedPolicy.
func (mr *MockCasbinMockRecorder) RemoveNamedPolicy(ptype any, params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ptype}, params...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNamedPolicy", reflect.TypeOf((*MockCasbin)(nil).RemoveNamedPolicy), varargs...)
}

// RemovePolicies mocks base method.
func (m *MockCasbin) RemovePolicies(rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePolicies", rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemovePolicies indicates an expected call of RemovePolicies.
func (mr *MockCasbinMockRecorder) RemovePolicies(rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePolicies", reflect.TypeOf((*MockCasbin)(nil).RemovePolicies), rules)
}

// RemovePolicy mocks base method.
func (m *MockCasbin) RemovePolicy(params ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemovePolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemovePolicy indicates an expected call of RemovePolicy.
func (mr *MockCasbinMockRecorder) RemovePolicy(params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePolicy", reflect.TypeOf((*MockCasbin)(nil).RemovePolicy), params...)
}

// SavePolicy mocks base method.
func (m *MockCasbin) SavePolicy() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePolicy")
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePolicy indicates an expected call of SavePolicy.
func (mr *MockCasbinMockRecorder) SavePolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePolicy", reflect.TypeOf((*MockCasbin)(nil).SavePolicy))
}

// SelfAddPolicies mocks base method.
func (m *MockCasbin) SelfAddPolicies(sec, ptype string, rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelfAddPolicies", sec, ptype, rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelfAddPolicies indicates an expected call of SelfAddPolicies.
func (mr *MockCasbinMockRecorder) SelfAddPolicies(sec, ptype, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelfAddPolicies", reflect.TypeOf((*MockCasbin)(nil).SelfAddPolicies), sec, ptype, rules)
}

// SelfAddPoliciesEx mocks base method.
func (m *MockCasbin) SelfAddPoliciesEx(sec, ptype string, rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelfAddPoliciesEx", sec, ptype, rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelfAddPoliciesEx indicates an expected call of SelfAddPoliciesEx.
func (mr *MockCasbinMockRecorder) SelfAddPoliciesEx(sec, ptype, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelfAddPoliciesEx", reflect.TypeOf((*MockCasbin)(nil).SelfAddPoliciesEx), sec, ptype, rules)
}

// SelfAddPolicy mocks base method.
func (m *MockCasbin) SelfAddPolicy(sec, ptype string, rule []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelfAddPolicy", sec, ptype, rule)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelfAddPolicy indicates an expected call of SelfAddPolicy.
func (mr *MockCasbinMockRecorder) SelfAddPolicy(sec, ptype, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelfAddPolicy", reflect.TypeOf((*MockCasbin)(nil).SelfAddPolicy), sec, ptype, rule)
}

// SelfRemoveFilteredPolicy mocks base method.
func (m *MockCasbin) SelfRemoveFilteredPolicy(sec, ptype string, fieldIndex int, fieldValues ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{sec, ptype, fieldIndex}
	for _, a := range fieldValues {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SelfRemoveFilteredPolicy", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelfRemoveFilteredPolicy indicates an expected call of SelfRemoveFilteredPolicy.
func (mr *MockCasbinMockRecorder) SelfRemoveFilteredPolicy(sec, ptype, fieldIndex any, fieldValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{sec, ptype, fieldIndex}, fieldValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelfRemoveFilteredPolicy", reflect.TypeOf((*MockCasbin)(nil).SelfRemoveFilteredPolicy), varargs...)
}

// SelfRemovePolicies mocks base method.
func (m *MockCasbin) SelfRemovePolicies(sec, ptype string, rules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelfRemovePolicies", sec, ptype, rules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelfRemovePolicies indicates an expected call of SelfRemovePolicies.
func (mr *MockCasbinMockRecorder) SelfRemovePolicies(sec, ptype, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelfRemovePolicies", reflect.TypeOf((*MockCasbin)(nil).SelfRemovePolicies), sec, ptype, rules)
}

// SelfRemovePolicy mocks base method.
func (m *MockCasbin) SelfRemovePolicy(sec, ptype string, rule []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelfRemovePolicy", sec, ptype, rule)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelfRemovePolicy indicates an expected call of SelfRemovePolicy.
func (mr *MockCasbinMockRecorder) SelfRemovePolicy(sec, ptype, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelfRemovePolicy", reflect.TypeOf((*MockCasbin)(nil).SelfRemovePolicy), sec, ptype, rule)
}

// SelfUpdatePolicies mocks base method.
func (m *MockCasbin) SelfUpdatePolicies(sec, ptype string, oldRules, newRules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelfUpdatePolicies", sec, ptype, oldRules, newRules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelfUpdatePolicies indicates an expected call of SelfUpdatePolicies.
func (mr *MockCasbinMockRecorder) SelfUpdatePolicies(sec, ptype, oldRules, newRules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelfUpdatePolicies", reflect.TypeOf((*MockCasbin)(nil).SelfUpdatePolicies), sec, ptype, oldRules, newRules)
}

// SelfUpdatePolicy mocks base method.
func (m *MockCasbin) SelfUpdatePolicy(sec, ptype string, oldRule, newRule []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelfUpdatePolicy", sec, ptype, oldRule, newRule)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelfUpdatePolicy indicates an expected call of SelfUpdatePolicy.
func (mr *MockCasbinMockRecorder) SelfUpdatePolicy(sec, ptype, oldRule, newRule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelfUpdatePolicy", reflect.TypeOf((*MockCasbin)(nil).SelfUpdatePolicy), sec, ptype, oldRule, newRule)
}

// SetAdapter mocks base method.
func (m *MockCasbin) SetAdapter(adapter persist.Adapter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAdapter", adapter)
}

// SetAdapter indicates an expected call of SetAdapter.
func (mr *MockCasbinMockRecorder) SetAdapter(adapter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAdapter", reflect.TypeOf((*MockCasbin)(nil).SetAdapter), adapter)
}

// SetEffector mocks base method.
func (m *MockCasbin) SetEffector(eft effector.Effector) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEffector", eft)
}

// SetEffector indicates an expected call of SetEffector.
func (mr *MockCasbinMockRecorder) SetEffector(eft any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEffector", reflect.TypeOf((*MockCasbin)(nil).SetEffector), eft)
}

// SetModel mocks base method.
func (m_2 *MockCasbin) SetModel(m model.Model) {
	m_2.ctrl.T.Helper()
	m_2.ctrl.Call(m_2, "SetModel", m)
}

// SetModel indicates an expected call of SetModel.
func (mr *MockCasbinMockRecorder) SetModel(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetModel", reflect.TypeOf((*MockCasbin)(nil).SetModel), m)
}

// SetRoleManager mocks base method.
func (m *MockCasbin) SetRoleManager(rm rbac.RoleManager) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRoleManager", rm)
}

// SetRoleManager indicates an expected call of SetRoleManager.
func (mr *MockCasbinMockRecorder) SetRoleManager(rm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoleManager", reflect.TypeOf((*MockCasbin)(nil).SetRoleManager), rm)
}

// SetWatcher mocks base method.
func (m *MockCasbin) SetWatcher(watcher persist.Watcher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWatcher", watcher)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWatcher indicates an expected call of SetWatcher.
func (mr *MockCasbinMockRecorder) SetWatcher(watcher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWatcher", reflect.TypeOf((*MockCasbin)(nil).SetWatcher), watcher)
}

// UpdateFilteredPolicies mocks base method.
func (m *MockCasbin) UpdateFilteredPolicies(newPolicies [][]string, fieldIndex int, fieldValues ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{newPolicies, fieldIndex}
	for _, a := range fieldValues {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateFilteredPolicies", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFilteredPolicies indicates an expected call of UpdateFilteredPolicies.
func (mr *MockCasbinMockRecorder) UpdateFilteredPolicies(newPolicies, fieldIndex any, fieldValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{newPolicies, fieldIndex}, fieldValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFilteredPolicies", reflect.TypeOf((*MockCasbin)(nil).UpdateFilteredPolicies), varargs...)
}

// UpdateGroupingPolicies mocks base method.
func (m *MockCasbin) UpdateGroupingPolicies(oldRules, newRules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroupingPolicies", oldRules, newRules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGroupingPolicies indicates an expected call of UpdateGroupingPolicies.
func (mr *MockCasbinMockRecorder) UpdateGroupingPolicies(oldRules, newRules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroupingPolicies", reflect.TypeOf((*MockCasbin)(nil).UpdateGroupingPolicies), oldRules, newRules)
}

// UpdateGroupingPolicy mocks base method.
func (m *MockCasbin) UpdateGroupingPolicy(oldRule, newRule []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroupingPolicy", oldRule, newRule)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGroupingPolicy indicates an expected call of UpdateGroupingPolicy.
func (mr *MockCasbinMockRecorder) UpdateGroupingPolicy(oldRule, newRule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroupingPolicy", reflect.TypeOf((*MockCasbin)(nil).UpdateGroupingPolicy), oldRule, newRule)
}

// UpdateNamedGroupingPolicies mocks base method.
func (m *MockCasbin) UpdateNamedGroupingPolicies(ptype string, oldRules, newRules [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNamedGroupingPolicies", ptype, oldRules, newRules)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNamedGroupingPolicies indicates an expected call of UpdateNamedGroupingPolicies.
func (mr *MockCasbinMockRecorder) UpdateNamedGroupingPolicies(ptype, oldRules, newRules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNamedGroupingPolicies", reflect.TypeOf((*MockCasbin)(nil).UpdateNamedGroupingPolicies), ptype, oldRules, newRules)
}

// UpdateNamedGroupingPolicy mocks base method.
func (m *MockCasbin) UpdateNamedGroupingPolicy(ptype string, oldRule, newRule []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNamedGroupingPolicy", ptype, oldRule, newRule)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNamedGroupingPolicy indicates an expected call of UpdateNamedGroupingPolicy.
func (mr *MockCasbinMockRecorder) UpdateNamedGroupingPolicy(ptype, oldRule, newRule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNamedGroupingPolicy", reflect.TypeOf((*MockCasbin)(nil).UpdateNamedGroupingPolicy), ptype, oldRule, newRule)
}

// UpdatePolicies mocks base method.
func (m *MockCasbin) UpdatePolicies(oldPolicies, newPolicies [][]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePolicies", oldPolicies, newPolicies)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePolicies indicates an expected call of UpdatePolicies.
func (mr *MockCasbinMockRecorder) UpdatePolicies(oldPolicies, newPolicies any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePolicies", reflect.TypeOf((*MockCasbin)(nil).UpdatePolicies), oldPolicies, newPolicies)
}

// UpdatePolicy mocks base method.
func (m *MockCasbin) UpdatePolicy(oldPolicy, newPolicy []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePolicy", oldPolicy, newPolicy)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePolicy indicates an expected call of UpdatePolicy.
func (mr *MockCasbinMockRecorder) UpdatePolicy(oldPolicy, newPolicy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePolicy", reflect.TypeOf((*MockCasbin)(nil).UpdatePolicy), oldPolicy, newPolicy)
}
